// resources/js/react/ConsentBanner.tsx
/**
 * ConsentBanner React component.
 *
 * A GDPR/CCPA-compliant cookie consent banner with accept, reject, and
 * customize options. Integrates with the consent API via the useConsent
 * hook and uses @artisanpack-ui/react Button and Card components.
 *
 * @since 1.1.0
 */

import React, { useEffect, useState } from 'react';
import { Button, Card, Toggle } from '@artisanpack-ui/react';

import { useConsent } from './useConsent';

import type { UseConsentOptions } from './useConsent';

export interface ConsentBannerProps extends UseConsentOptions {
    /** Banner position on screen. Defaults to 'bottom'. */
    position?: 'top' | 'bottom';
    /** Title text for the banner. */
    title?: string;
    /** Description text displayed below the title. */
    description?: string;
    /** Label for the accept all button. */
    acceptLabel?: string;
    /** Label for the reject all button. */
    rejectLabel?: string;
    /** Label for the customize button. */
    customizeLabel?: string;
    /** Label for the save preferences button. */
    saveLabel?: string;
    /** Callback invoked after consent is saved. */
    onConsentSaved?: ( categories: Record<string, boolean> ) => void;
    /** Optional CSS class name for the container. */
    className?: string;
}

export default function ConsentBanner( {
    position = 'bottom',
    title = 'Privacy Settings',
    description = 'We use cookies to understand how you use our website and improve your experience.',
    acceptLabel = 'Accept All',
    rejectLabel = 'Reject All',
    customizeLabel = 'Customize',
    saveLabel = 'Save Preferences',
    onConsentSaved,
    className = '',
    ...consentOptions
}: ConsentBannerProps ): React.ReactElement | null {
    const {
        loading,
        consentRequired,
        categories,
        acceptAll,
        rejectAll,
        updateConsent,
    } = useConsent( consentOptions );

    const [ visible, setVisible ] = useState( false );
    const [ showDetails, setShowDetails ] = useState( false );
    const [ localCategories, setLocalCategories ] = useState<Record<string, boolean>>( {} );

    // Show the banner if consent is required and no consent has been given yet
    useEffect( () => {
        if ( ! consentRequired ) {
            return;
        }

        const stored = typeof localStorage !== 'undefined'
            ? localStorage.getItem( 'ap_analytics_consent' )
            : null;

        if ( ! stored ) {
            setVisible( true );
        }
    }, [ consentRequired ] );

    // Sync local toggle state with API categories
    useEffect( () => {
        const state: Record<string, boolean> = {};

        for ( const [ key, item ] of Object.entries( categories ) ) {
            state[ key ] = item.required || item.granted;
        }

        setLocalCategories( state );
    }, [ categories ] );

    if ( ! visible ) {
        return null;
    }

    const handleAcceptAll = async (): Promise<void> => {
        try {
            await acceptAll();
            setVisible( false );
            onConsentSaved?.( Object.fromEntries(
                Object.keys( categories ).map( ( key ) => [ key, true ] ),
            ) );
        } catch ( err ) {
            console.error( 'Failed to accept all consent:', err );
        }
    };

    const handleRejectAll = async (): Promise<void> => {
        try {
            await rejectAll();
            setVisible( false );

            const result: Record<string, boolean> = {};

            for ( const [ key, item ] of Object.entries( categories ) ) {
                result[ key ] = item.required;
            }

            onConsentSaved?.( result );
        } catch ( err ) {
            console.error( 'Failed to reject all consent:', err );
        }
    };

    const handleSavePreferences = async (): Promise<void> => {
        try {
            await updateConsent( localCategories );
            setVisible( false );
            onConsentSaved?.( { ...localCategories } );
        } catch ( err ) {
            console.error( 'Failed to save consent preferences:', err );
        }
    };

    const handleToggleCategory = ( key: string, value: boolean ): void => {
        if ( categories[ key ]?.required ) {
            return;
        }

        setLocalCategories( ( prev ) => ( { ...prev, [ key ]: value } ) );
    };

    const positionClasses = position === 'bottom'
        ? 'bottom-0'
        : 'top-0';

    return (
        <div
            className={`fixed ${positionClasses} inset-x-0 z-50 p-4 ${className}`.trim()}
            role="dialog"
            aria-modal="true"
            aria-labelledby="consent-banner-title"
        >
            <div className="mx-auto max-w-4xl">
                <Card>
                    <div className="flex items-start justify-between mb-4">
                        <div>
                            <h3
                                id="consent-banner-title"
                                className="text-lg font-semibold"
                            >
                                {title}
                            </h3>
                            <p className="text-sm opacity-70 mt-1">
                                {description}
                            </p>
                        </div>
                        <Button
                            color="ghost"
                            size="sm"
                            onClick={() => setShowDetails( ! showDetails )}
                            aria-expanded={showDetails}
                            aria-controls="consent-details"
                        >
                            {showDetails ? 'Hide Details' : customizeLabel}
                        </Button>
                    </div>

                    {showDetails && (
                        <div id="consent-details" className="space-y-3 mb-6">
                            {Object.entries( categories ).map( ( [ key, item ] ) => (
                                <label
                                    key={key}
                                    className="flex items-start gap-3 p-3 rounded-lg bg-base-200/50"
                                >
                                    <div className="mt-1">
                                        <Toggle
                                            checked={localCategories[ key ] ?? false}
                                            onChange={( e ) => handleToggleCategory( key, e.target.checked )}
                                            disabled={item.required}
                                            size="sm"
                                            color="primary"
                                        />
                                    </div>
                                    <div className="flex-1">
                                        <span className="font-medium">
                                            {item.name}
                                            {item.required && (
                                                <span className="text-xs opacity-50 ml-1">
                                                    (Required)
                                                </span>
                                            )}
                                        </span>
                                        <p className="text-sm opacity-70 mt-0.5">
                                            {item.description}
                                        </p>
                                    </div>
                                </label>
                            ) )}
                        </div>
                    )}

                    <div className="flex flex-wrap items-center justify-end gap-3">
                        <Button
                            color="ghost"
                            size="sm"
                            onClick={handleRejectAll}
                            disabled={loading}
                        >
                            {rejectLabel}
                        </Button>
                        {showDetails && (
                            <Button
                                color="neutral"
                                size="sm"
                                onClick={handleSavePreferences}
                                disabled={loading}
                            >
                                {saveLabel}
                            </Button>
                        )}
                        <Button
                            color="primary"
                            size="sm"
                            onClick={handleAcceptAll}
                            disabled={loading}
                        >
                            {acceptLabel}
                        </Button>
                    </div>
                </Card>
            </div>
        </div>
    );
}

// resources/js/vue/ConsentBanner.vue
<!--
  ConsentBanner Vue component.

  A GDPR/CCPA-compliant cookie consent banner with accept, reject, and
  customize options. Integrates with the consent API via the useConsent
  composable and uses @artisanpack-ui/vue Button, Card, and Toggle
  components.

  @since 1.1.0
-->
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { Button, Card, Toggle } from '@artisanpack-ui/vue';

import { useConsent } from './useConsent';

import type { UseConsentOptions } from './useConsent';

interface Props extends UseConsentOptions {
    /** Banner position on screen. Defaults to 'bottom'. */
    position?: 'top' | 'bottom';
    /** Title text for the banner. */
    title?: string;
    /** Description text displayed below the title. */
    description?: string;
    /** Label for the accept all button. */
    acceptLabel?: string;
    /** Label for the reject all button. */
    rejectLabel?: string;
    /** Label for the customize button. */
    customizeLabel?: string;
    /** Label for the save preferences button. */
    saveLabel?: string;
}

const props = withDefaults( defineProps<Props>(), {
    position: 'bottom',
    title: 'Privacy Settings',
    description: 'We use cookies to understand how you use our website and improve your experience.',
    acceptLabel: 'Accept All',
    rejectLabel: 'Reject All',
    customizeLabel: 'Customize',
    saveLabel: 'Save Preferences',
    apiPrefix: 'api/analytics',
    fetchOnMount: true,
    initialConsentRequired: false,
    initialCategories: () => ( {} ),
} );

const emit = defineEmits<{
    consentSaved: [categories: Record<string, boolean>];
}>();

const {
    loading,
    consentRequired,
    categories,
    acceptAll,
    rejectAll,
    updateConsent,
} = useConsent( {
    apiPrefix: props.apiPrefix,
    fetchOnMount: props.fetchOnMount,
    initialCategories: props.initialCategories,
    initialConsentRequired: props.initialConsentRequired,
} );

const visible = ref( false );
const showDetails = ref( false );
const localCategories = ref<Record<string, boolean>>( {} );

onMounted( () => {
    if ( ! consentRequired.value ) {
        return;
    }

    const stored = typeof localStorage !== 'undefined'
        ? localStorage.getItem( 'ap_analytics_consent' )
        : null;

    if ( ! stored ) {
        visible.value = true;
    }
} );

watch( () => consentRequired.value, ( required ) => {
    if ( ! required ) {
        return;
    }

    const stored = typeof localStorage !== 'undefined'
        ? localStorage.getItem( 'ap_analytics_consent' )
        : null;

    if ( ! stored ) {
        visible.value = true;
    }
} );

watch( categories, ( cats ) => {
    const state: Record<string, boolean> = {};

    for ( const [ key, item ] of Object.entries( cats ) ) {
        state[ key ] = item.required || item.granted;
    }

    localCategories.value = state;
}, { immediate: true } );

async function handleAcceptAll(): Promise<void> {
    await acceptAll();
    visible.value = false;
    emit( 'consentSaved', Object.fromEntries(
        Object.keys( categories.value ).map( ( key ) => [ key, true ] ),
    ) );
}

async function handleRejectAll(): Promise<void> {
    await rejectAll();
    visible.value = false;

    const result: Record<string, boolean> = {};

    for ( const [ key, item ] of Object.entries( categories.value ) ) {
        result[ key ] = item.required;
    }

    emit( 'consentSaved', result );
}

async function handleSavePreferences(): Promise<void> {
    await updateConsent( localCategories.value );
    visible.value = false;
    emit( 'consentSaved', { ...localCategories.value } );
}

function handleToggleCategory( key: string, value: boolean ): void {
    if ( categories.value[ key ]?.required ) {
        return;
    }

    localCategories.value[ key ] = value;
}
</script>

<template>
    <div
        v-if="visible"
        :class="[
            'fixed inset-x-0 z-50 p-4',
            props.position === 'bottom' ? 'bottom-0' : 'top-0',
        ]"
        role="dialog"
        aria-modal="true"
        aria-labelledby="consent-banner-title"
    >
        <div class="mx-auto max-w-4xl">
            <Card>
                <div class="flex items-start justify-between mb-4">
                    <div>
                        <h3
                            id="consent-banner-title"
                            class="text-lg font-semibold"
                        >
                            {{ props.title }}
                        </h3>
                        <p class="text-sm opacity-70 mt-1">
                            {{ props.description }}
                        </p>
                    </div>
                    <Button
                        color="ghost"
                        size="sm"
                        :aria-expanded="showDetails"
                        aria-controls="consent-details"
                        @click="showDetails = ! showDetails"
                    >
                        {{ showDetails ? 'Hide Details' : props.customizeLabel }}
                    </Button>
                </div>

                <div v-if="showDetails" id="consent-details" class="space-y-3 mb-6">
                    <label
                        v-for="( item, key ) in categories"
                        :key="key"
                        class="flex items-start gap-3 p-3 rounded-lg bg-base-200/50"
                    >
                        <div class="mt-1">
                            <Toggle
                                :model-value="localCategories[ key as string ] ?? false"
                                :disabled="item.required"
                                size="sm"
                                color="primary"
                                @update:model-value="handleToggleCategory( key as string, $event as boolean )"
                            />
                        </div>
                        <div class="flex-1">
                            <span class="font-medium">
                                {{ item.name }}
                                <span v-if="item.required" class="text-xs opacity-50 ml-1">
                                    (Required)
                                </span>
                            </span>
                            <p class="text-sm opacity-70 mt-0.5">
                                {{ item.description }}
                            </p>
                        </div>
                    </label>
                </div>

                <div class="flex flex-wrap items-center justify-end gap-3">
                    <Button
                        color="ghost"
                        size="sm"
                        :disabled="loading"
                        @click="handleRejectAll"
                    >
                        {{ props.rejectLabel }}
                    </Button>
                    <Button
                        v-if="showDetails"
                        color="neutral"
                        size="sm"
                        :disabled="loading"
                        @click="handleSavePreferences"
                    >
                        {{ props.saveLabel }}
                    </Button>
                    <Button
                        color="primary"
                        size="sm"
                        :disabled="loading"
                        @click="handleAcceptAll"
                    >
                        {{ props.acceptLabel }}
                    </Button>
                </div>
            </Card>
        </div>
    </div>
</template>
