// resources/js/react/widgets/TopPages.tsx
/**
 * TopPages React component.
 *
 * Displays a sortable table of the most visited pages using
 * @artisanpack-ui/react Table component. Mirrors the Livewire
 * TopPages widget.
 *
 * @since 1.1.0
 */

import React from 'react';
import { Card, Table } from '@artisanpack-ui/react';

import type { TableHeader } from '@artisanpack-ui/react';
import type { TopPageItem } from '../../types';

export interface TopPagesProps {
    /** Array of top page data from the API. */
    topPages: TopPageItem[];
    /** Maximum number of pages to display. */
    limit?: number;
    /** Optional CSS class name for the container. */
    className?: string;
}

const headers: TableHeader<TopPageItem>[] = [
    { key: 'path', label: 'Page', sortable: true },
    { key: 'views', label: 'Views', sortable: true },
    { key: 'unique_views', label: 'Unique Views', sortable: true },
];

export default function TopPages( {
    topPages,
    limit = 10,
    className = '',
}: TopPagesProps ): React.ReactElement {
    const displayData = topPages.slice( 0, limit );

    return (
        <Card title="Top Pages" className={className}>
            <Table<TopPageItem>
                headers={headers}
                rows={displayData}
                striped
            />
        </Card>
    );
}

// resources/js/vue/widgets/TopPages.vue
<!--
  TopPages Vue component.

  Displays a sortable table of the most visited pages using
  @artisanpack-ui/vue Table component. Mirrors the Livewire
  TopPages widget.

  @since 1.1.0
-->
<script setup lang="ts">
import { computed } from 'vue';
import { Card, Table } from '@artisanpack-ui/vue';

import type { TableColumn } from '@artisanpack-ui/vue';
import type { TopPageItem } from '../../types';

const props = withDefaults( defineProps<{
    /** Array of top page data from the API. */
    topPages: TopPageItem[];
    /** Maximum number of pages to display. */
    limit?: number;
}>(), {
    limit: 10,
} );

const columns: TableColumn[] = [
    { key: 'path', label: 'Page', sortable: true },
    { key: 'views', label: 'Views', sortable: true },
    { key: 'unique_views', label: 'Unique Views', sortable: true },
];

const displayData = computed( () => {
    const clampedLimit = Math.max( 0, Math.floor( props.limit ) );

    return props.topPages.slice( 0, clampedLimit );
} );
</script>

<template>
    <Card title="Top Pages">
        <Table
            :columns="columns"
            :rows="displayData"
            striped
            :empty-message="'No page data available for this period.'"
        />
    </Card>
</template>
