// resources/js/vue/ConsentStatus.vue
<!--
  ConsentStatus Vue component.

  A small indicator showing the current consent state. Can be used as a
  persistent UI element to let users revisit their consent preferences.
  Uses @artisanpack-ui/vue Badge and Button components.

  @since 1.1.0
-->
<script setup lang="ts">
import { computed } from 'vue';
import { Badge, Button } from '@artisanpack-ui/vue';

import { useConsent } from './useConsent';

import type { UseConsentOptions } from './useConsent';

interface Props extends UseConsentOptions {
    /** Label text for the status indicator. */
    label?: string;
    /** Label for the manage button. */
    manageLabel?: string;
    /** Whether to show the manage button. Defaults to true. */
    showManageButton?: boolean;
}

const props = withDefaults( defineProps<Props>(), {
    label: 'Privacy',
    manageLabel: 'Manage',
    showManageButton: true,
    apiPrefix: 'api/analytics',
    fetchOnMount: true,
    initialConsentRequired: false,
    initialCategories: () => ( {} ),
} );

const emit = defineEmits<{
    manageClick: [];
}>();

const { consentRequired, categories } = useConsent( {
    apiPrefix: props.apiPrefix,
    fetchOnMount: props.fetchOnMount,
    initialCategories: props.initialCategories,
    initialConsentRequired: props.initialConsentRequired,
} );

const totalCategories = computed( () => Object.keys( categories.value ).length );
const grantedCount = computed( () =>
    Object.values( categories.value ).filter( ( c ) => c.granted ).length,
);
const allGranted = computed( () =>
    totalCategories.value > 0 && grantedCount.value === totalCategories.value,
);
const noneGranted = computed( () =>
    totalCategories.value > 0 && grantedCount.value === 0,
);

const statusColor = computed( (): 'success' | 'warning' | 'error' => {
    if ( allGranted.value ) {
        return 'success';
    }

    if ( noneGranted.value ) {
        return 'error';
    }

    return 'warning';
} );

const statusText = computed( () => {
    if ( allGranted.value ) {
        return 'All accepted';
    }

    if ( noneGranted.value ) {
        return 'None accepted';
    }

    return `${grantedCount.value}/${totalCategories.value}`;
} );
</script>

<template>
    <div
        v-if="consentRequired"
        class="inline-flex items-center gap-2"
    >
        <span class="text-sm font-medium">{{ props.label }}</span>
        <Badge :color="statusColor" size="sm">
            {{ statusText }}
        </Badge>
        <Button
            v-if="props.showManageButton"
            color="ghost"
            size="xs"
            @click="emit( 'manageClick' )"
        >
            {{ props.manageLabel }}
        </Button>
    </div>
</template>

// resources/js/react/ConsentStatus.tsx
/**
 * ConsentStatus React component.
 *
 * A small indicator showing the current consent state. Can be used as a
 * persistent UI element to let users revisit their consent preferences.
 * Uses @artisanpack-ui/react Badge and Button components.
 *
 * @since 1.1.0
 */

import React from 'react';
import { Badge, Button } from '@artisanpack-ui/react';

import { useConsent } from './useConsent';

import type { UseConsentOptions } from './useConsent';

export interface ConsentStatusProps extends UseConsentOptions {
    /** Label text for the status indicator. */
    label?: string;
    /** Callback when the user clicks to manage preferences. */
    onManageClick?: () => void;
    /** Label for the manage button. */
    manageLabel?: string;
    /** Whether to show the manage button. Defaults to true. */
    showManageButton?: boolean;
    /** Optional CSS class name for the container. */
    className?: string;
}

export default function ConsentStatus( {
    label = 'Privacy',
    onManageClick,
    manageLabel = 'Manage',
    showManageButton = true,
    className = '',
    ...consentOptions
}: ConsentStatusProps ): React.ReactElement | null {
    const { consentRequired, categories } = useConsent( consentOptions );

    if ( ! consentRequired ) {
        return null;
    }

    const totalCategories = Object.keys( categories ).length;
    const grantedCount = Object.values( categories ).filter( ( c ) => c.granted ).length;
    const allGranted = totalCategories > 0 && grantedCount === totalCategories;
    const noneGranted = totalCategories > 0 && grantedCount === 0;

    let statusColor: 'success' | 'warning' | 'error' = 'warning';
    let statusText = `${grantedCount}/${totalCategories}`;

    if ( allGranted ) {
        statusColor = 'success';
        statusText = 'All accepted';
    } else if ( noneGranted ) {
        statusColor = 'error';
        statusText = 'None accepted';
    }

    return (
        <div className={`inline-flex items-center gap-2 ${className}`.trim()}>
            <span className="text-sm font-medium">{label}</span>
            <Badge color={statusColor} size="sm">{statusText}</Badge>
            {showManageButton && onManageClick && (
                <Button
                    color="ghost"
                    size="xs"
                    onClick={onManageClick}
                >
                    {manageLabel}
                </Button>
            )}
        </div>
    );
}
